version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: rust:1.44.1
    steps:
      - checkout
      - run:
          name: apt-get
          command: apt-get update && apt-get -y install lcov ruby
      - run:
          name: rustup install nightly
          command: rustup install nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown
      - run:
          name: Unit tests
          env: RUST_BACKTRACE=1
          command: cargo unit-test --locked
      - run:
          name: Build
          command: cargo wasm --locked
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: lint
          command: cargo clippy --all-targets -- -D warnings
      - run:
          name: Format source code
          command: cargo fmt
      - run:
          name: cargo install grcov
          command: |
            gem install coveralls-lcov
            cargo install grcov
      - run:
          name: generate coverage
          command: |
            PROJ_NAME=$(cat Cargo.toml | grep -E "^name" | sed -E 's/name[[:space:]]=[[:space:]]"(.*)"/\1/g' | sed -E 's/-/_/g')
            rm -rf target/debug/deps/${PROJ_NAME}-*
            
            export CARGO_INCREMENTAL=0
            export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
            
            cargo +nightly build --verbose
            cargo +nightly test --verbose
            
            grcov ./target/debug/deps -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
            genhtml -o report/ --show-details --highlight --ignore-errors source --legend lcov.info
      - codecov/upload:
          file: lcov.info
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/wasm32-unknown-unknown/release/.fingerprint
            - target/wasm32-unknown-unknown/release/build
            - target/wasm32-unknown-unknown/release/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
          